config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'tasks',          to: 'tasks#index'

  # get 'tasks/new',      to: 'tasks#new'
  # post 'tasks',         to: 'tasks#create'

  # get 'tasks/:id',      to: 'tasks#show', as: :tasks_show

  # get 'tasks/:id/edit', to: 'tasks#edit', as: :tasks_edit
  # patch 'tasks/:id',    to: 'tasks#update', as: :task

  # delete 'tasks/:id',   to: 'tasks#delete', as: :tasks_delete

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # filters
  before_action :find, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(strong_params)
    if @task.save!
      redirect_to task_path(@task.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(strong_params)
      redirect_to task_path(@task.id)
    end
  end

  def destroy
    if @task.destroy
      redirect_to tasks_path
    end
  end

  private

  def find
    @task = Task.find(params[:id])
  end

  def strong_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, value: @task.title %>
  <%= f.label :details %>
  <%= f.text_field :details, value: @task.details %>

  <%= f.check_box :completed %>
  <%= f.label :completed, @task.completed ? "Mark as not completed" : "Mark as completed" %>
  <%= f.submit %>
<% end %>
<div>
  <%= link_to "Back to List", tasks_path %>
</div>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
  <li>
    <%= task.completed ? "☑️" : "◻️" %>
    <%= link_to task.title, task_path(task.id) %>
    <%= link_to "Delete", task_path(task), method: :delete, data: { confirm: "Are you sure you want to delete #{task.title}?" }  %>
  </li>
  <% end %>
</ul>

<div>
  <%= link_to "Add new task", new_task_path %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>
<div>
  <%= link_to "Back to List", tasks_path %>
</div>

app/views/tasks/show.html.erb
<h1><%= @task.title %> </h1>
<div><%= @task.details %> </div>
<div><%= @task.completed ? "☑️ This task is completed" : "◻️ This task is not completed yet" %> </div>
<div>
  <%= link_to "Edit this task", edit_task_path %>
</div>
<div>
  <%= link_to "Back to List", tasks_path %>
</div>